const english={navAbout:'About us',navProducts:'What we make',navProduction:'Production',navContact:'Contact',heroLabel:'WOOD. PLYWOOD. CRAFT.',heroTitle:'Your idea<br><em>Our craft</em>',heroText:'Custom wood and plywood products, made at our production facility in Valmiera, Latvia.',heroButton:'Tell us about your idea',aboutLabel:'ABOUT US',aboutTitle:'Giving your ideas<br>form in wood',aboutText:'PlyCraft is a Latvian manufacturer. We turn your concept into a finished wood or plywood product.',aboutMore:'Furniture, components and bespoke solutions — made to your design, dimensions and chosen finish.',aboutLink:'Explore what we can make',productsLabel:'WHAT WE MAKE',productsTitle:'Made for your project',productsIntro:'From a single component to a finished product.',p1Title:'Furniture & components',p1Text:'Wood and plywood furniture, structures and components made to your drawings.',p2Title:'Bespoke orders',p2Text:'Dimensions, shapes and solutions tailored to your space and requirements.',p3Title:'Processing & finishing',p3Text:'Component preparation, sanding, assembly and painting to suit your order.',productionLabel:'PRODUCTION IN VALMIERA',productionTitle:'Where your project<br>takes shape',productionText:'Spacious production facilities. Careful work. Attention to detail.',productionMore:'From preparing the material to applying the finish — every stage contributes to the final result.',processLabel:'FROM CONCEPT TO FINISHED PRODUCT',processTitle:'Let’s start with your idea',step1:'Send us your idea, sketch or drawing.',step2:'We agree on materials, finish and timing.',step3:'We manufacture your order.',processLink:'Contact PlyCraft',contactLabel:'CONTACT',contactTitle:'Let’s make something lasting',factory:'Production: Valmiera, Latvia',reg:'Registration No.',vat:'VAT No.',address:'Registered address:',addressValue:'Sesku iela 46, Rīga, LV-1082, Latvia',top:'Back to top ↑',a1:'PlyCraft craftsperson at the production facility',a2:'Sanding a product surface',a3:'Manufacturing wooden components',a4:'Components on production racks',a5:'Working at the PlyCraft production facility',a6:'Prepared wooden components',a7:'Assembling a product',a8:'Products during finishing',a9:'Painting components',a10:'Painted components during finishing'};
Object.assign(english,{"heroLabel": "WOOD & PLYWOOD MANUFACTURING", "heroTitle": "Your vision<br><em>Our capability</em>", "heroText": "A strong team. Purposeful production. Wood and plywood solutions for your business.", "heroButton": "Discuss your project", "aboutTitle": "A team that<br>makes it happen", "aboutText": "We are PlyCraft — a wood and plywood manufacturer in Latvia. Our team brings the skills and production capability to realise your project.", "aboutMore": "From bespoke orders to series production. Furniture, components and solutions for businesses in Latvia and abroad.", "productsTitle": "Your project<br>Made by PlyCraft", "p1Text": "Furniture, structures and components made to your drawings.", "p2Text": "Dimensions, materials and shapes tailored to your project.", "p3Text": "Component preparation, sanding, assembly and painting.", "productionLabel": "OUR PRODUCTION", "productionTitle": "From the first component<br>To the finished order", "productionText": "A spacious facility in Valmiera. One team. A connected process.", "productionMore": "Materials, machining, assembly, finishing. Every stage matters. Every order gets our attention.", "a11": "Plywood materials at the production facility", "a12": "Close-up of wood processing", "a13": "Woodworking equipment", "a14": "PlyCraft craftsperson at work"});
Object.assign(english,{contactLabel:'LET’S TALK',contactTitle:'Your idea starts here',contactIntro:'Tell us about your project — together we will find the right solution.',formName:'Your name *',formCompany:'Company',formEmail:'Email *',formMessage:'About your project *',formNote:'We will prepare a message in your email app. You can attach drawings and photos before sending.',formSubmit:'Prepare enquiry ↗'});
Object.assign(english,{"heroLabel": "FURNITURE & WOOD MANUFACTURING", "heroTitle": "Your vision<br><em>Carefully made</em>", "heroText": "Furniture and plywood products that bring together the character of wood and considered craftsmanship", "heroButton": "Discuss your project", "aboutTitle": "Character in the material<br>Care in the making", "aboutText": "PlyCraft is a furniture, wood and plywood manufacturer in Latvia — a production partner for bringing your designs to life", "aboutMore": "From bespoke pieces to production runs, we tailor materials, construction and finishes to the requirements of each project", "aboutLink": "Explore our capabilities", "productsTitle": "Made for<br>your project", "productsIntro": "Furniture and components for interiors, commercial spaces and your product collections", "p1Title": "Furniture & components", "p1Text": "Wood and plywood furniture, structures and components made to your drawings and technical specification", "p2Title": "Bespoke solutions", "p2Text": "Dimensions, forms and materials tailored to your project — from a single piece to a coordinated series", "p3Title": "Processing & finishing", "p3Text": "Component preparation, sanding, assembly and painting to achieve the intended finish", "productionTitle": "Care at every<br>stage of production", "productionText": "At our facility in Valmiera, your drawings take shape as finished products", "productionMore": "Material preparation, machining, assembly and finishing come together in a coordinated process guided by your project requirements", "processLabel": "WORKING TOGETHER", "processTitle": "From concept to completion", "step1": "Share your concept, sketch or drawing", "step2": "Together we agree on materials, finishes and timing", "step3": "We manufacture to the agreed specification", "contactLabel": "YOUR NEXT PROJECT", "contactTitle": "Let’s give your vision form", "contactIntro": "Tell us what you would like to create — we will discuss the details and production possibilities", "formNote": "Your enquiry opens in your email app — attach drawings and photographs there before sending", "reg": "Registration number", "vat": "VAT number", "address": "Registered address", "factory": "Production in Valmiera, Latvia"});
const elements=[...document.querySelectorAll('[data-i]')], images=[...document.querySelectorAll('[data-alt]')];
const latvian=Object.fromEntries(elements.map(el=>[el.dataset.i,el.innerHTML]));images.forEach(el=>latvian[el.dataset.alt]=el.alt);
function setLanguage(lang){if(!['lv','en'].includes(lang))lang='lv';const copy=lang==='en'?english:latvian;elements.forEach(el=>el.innerHTML=copy[el.dataset.i]);images.forEach(el=>el.alt=copy[el.dataset.alt]);document.documentElement.lang=lang;document.querySelectorAll('[data-lang]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.lang===lang)));document.querySelector('meta[name="description"]').content=lang==='en'?'PlyCraft — custom wood and plywood products. Manufacturing in Valmiera, Latvia.':'PlyCraft — koka un saplākšņa izstrādājumi pēc pasūtījuma. Ražošana Valmierā, Latvijā.';try{localStorage.setItem('plycraft-language',lang)}catch{}const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url);}
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>setLanguage(button.dataset.lang)));let initial='lv';try{initial=localStorage.getItem('plycraft-language')||'lv'}catch{}setLanguage(new URL(location.href).searchParams.get('lang')||initial);
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));document.documentElement.classList.add('motion');}

const address=String.fromCharCode(105,110,102,111,64,112,108,121,99,114,97,102,116,46,101,117);
document.querySelectorAll('[data-email]').forEach(a=>{a.textContent=address;a.href='mailto:'+address});
document.querySelector('#project-form').addEventListener('submit',event=>{
 event.preventDefault();const form=event.currentTarget; if(!form.reportValidity())return;
 const data=new FormData(form);const en=document.documentElement.lang==='en';
 const subject=(en?'Project enquiry — ':'Projekta pieteikums — ')+(data.get('company')||data.get('name'));
 const body=[(en?'Name: ':'Vārds: ')+data.get('name'),(en?'Company: ':'Uzņēmums: ')+data.get('company'),(en?'Email: ':'E-pasts: ')+data.get('email'),'',data.get('message')].join('\n');
 window.location.href='mailto:'+address+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);
 document.querySelector('.form-status').textContent=en?'Send the prepared message from your email app. If it does not open, use the email address alongside.':'Nosūtiet sagatavoto vēstuli savā e-pasta lietotnē. Ja tā neatveras, izmantojiet blakus norādīto e-pasta adresi.';
});
